### ISSUE TITLE
PID vs LQR

### ISSUE THREAD

**Issue by amons02** [surfdado/bldc#2]
I've been interested in making a VESC board and was looking at this repo. Just out of curiosity, I was wondering why PID is used instead of LQR. Does FM use PID, or does it maybe make the control loop run faster? In my mind I was thinking that an LQR could maybe give a smoother feel by penalizing angular rate, but that's just a random thought.

**Comment by surfdado** [comment]
hi there, to be honest I have no background in control systems and I have never heard of LQR. We don't know what FM uses but whatever it is our VESC boards now feel extremely similar to theirs
